//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrwSoftware {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrwUtilsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrwUtilsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrwSoftware.FrwUtilsRes", typeof(FrwUtilsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string Attribute_Identifier {
            get {
                return ResourceManager.GetString("Attribute_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout widgets screen.
        /// </summary>
        internal static string Attribute_Layout_Of_Screen_Widgets {
            get {
                return ResourceManager.GetString("Attribute_Layout_Of_Screen_Widgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Attribute_Name {
            get {
                return ResourceManager.GetString("Attribute_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml.
        /// </summary>
        internal static string Attribute_Xml {
            get {
                return ResourceManager.GetString("Attribute_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Dm_Total {
            get {
                return ResourceManager.GetString("Dm_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in entity.
        /// </summary>
        internal static string Dm_UsedInEntity {
            get {
                return ResourceManager.GetString("Dm_UsedInEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string JCountry_Country {
            get {
                return ResourceManager.GetString("JCountry_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        internal static string JCountry_Flag {
            get {
                return ResourceManager.GetString("JCountry_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string JCountry_Identifier {
            get {
                return ResourceManager.GetString("JCountry_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string JCountry_Name {
            get {
                return ResourceManager.GetString("JCountry_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string JJobType {
            get {
                return ResourceManager.GetString("JJobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocurrent type .
        /// </summary>
        internal static string JJobType_ConcurrentType {
            get {
                return ResourceManager.GetString("JJobType_ConcurrentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is cancelable.
        /// </summary>
        internal static string JJobType_IsCancelable {
            get {
                return ResourceManager.GetString("JJobType_IsCancelable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string JJobType_JJobTypeId {
            get {
                return ResourceManager.GetString("JJobType_JJobTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last batch run date.
        /// </summary>
        internal static string JJobType_JobBatchLastRunDate {
            get {
                return ResourceManager.GetString("JJobType_JobBatchLastRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress %.
        /// </summary>
        internal static string JJobType_JobBatchProgress {
            get {
                return ResourceManager.GetString("JJobType_JobBatchProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queried jobs count.
        /// </summary>
        internal static string JJobType_JobBatchQueueCount {
            get {
                return ResourceManager.GetString("JJobType_JobBatchQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running jobs count.
        /// </summary>
        internal static string JJobType_JobBatchRunningCount {
            get {
                return ResourceManager.GetString("JJobType_JobBatchRunningCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch stage.
        /// </summary>
        internal static string JJobType_JobBatchStage {
            get {
                return ResourceManager.GetString("JJobType_JobBatchStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last job run date.
        /// </summary>
        internal static string JJobType_LastRunDate {
            get {
                return ResourceManager.GetString("JJobType_LastRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last stage of job run.
        /// </summary>
        internal static string JJobType_LastStage {
            get {
                return ResourceManager.GetString("JJobType_LastStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum threads.
        /// </summary>
        internal static string JJobType_MaxThreadCount {
            get {
                return ResourceManager.GetString("JJobType_MaxThreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string JJobType_Name {
            get {
                return ResourceManager.GetString("JJobType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string JNotification {
            get {
                return ResourceManager.GetString("JNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        internal static string JNotification_CreatedDate {
            get {
                return ResourceManager.GetString("JNotification_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string JNotification_Description {
            get {
                return ResourceManager.GetString("JNotification_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string JNotification_IsArchive {
            get {
                return ResourceManager.GetString("JNotification_IsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string JNotification_JNotificationId {
            get {
                return ResourceManager.GetString("JNotification_JNotificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string JNotification_NotificationType {
            get {
                return ResourceManager.GetString("JNotification_NotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source identifier.
        /// </summary>
        internal static string JNotification_SrcId {
            get {
                return ResourceManager.GetString("JNotification_SrcId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string JNotification_SrcType {
            get {
                return ResourceManager.GetString("JNotification_SrcType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string JNotification_Title {
            get {
                return ResourceManager.GetString("JNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job batch.
        /// </summary>
        internal static string Job_batch {
            get {
                return ResourceManager.GetString("Job_batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job batch canceled.
        /// </summary>
        internal static string Job_batch_canceled {
            get {
                return ResourceManager.GetString("Job_batch_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job batch completed.
        /// </summary>
        internal static string Job_batch_completed {
            get {
                return ResourceManager.GetString("Job_batch_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string JPreferences {
            get {
                return ResourceManager.GetString("JPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string JPreferences_Identifier {
            get {
                return ResourceManager.GetString("JPreferences_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences Name.
        /// </summary>
        internal static string JPreferences_Name {
            get {
                return ResourceManager.GetString("JPreferences_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job type.
        /// </summary>
        internal static string JRunningJob {
            get {
                return ResourceManager.GetString("JRunningJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        internal static string JRunningJob_CreateDate {
            get {
                return ResourceManager.GetString("JRunningJob_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string JRunningJob_JJobType {
            get {
                return ResourceManager.GetString("JRunningJob_JJobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string JRunningJob_JRunningJobId {
            get {
                return ResourceManager.GetString("JRunningJob_JRunningJobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string JRunningJob_Name {
            get {
                return ResourceManager.GetString("JRunningJob_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress%.
        /// </summary>
        internal static string JRunningJob_Progress {
            get {
                return ResourceManager.GetString("JRunningJob_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        internal static string JRunningJob_Stage {
            get {
                return ResourceManager.GetString("JRunningJob_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent.
        /// </summary>
        internal static string JUserAgent {
            get {
                return ResourceManager.GetString("JUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string JUserAgent_Alias {
            get {
                return ResourceManager.GetString("JUserAgent_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string JUserAgent_Data {
            get {
                return ResourceManager.GetString("JUserAgent_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string JUserAgent_JUserAgentId {
            get {
                return ResourceManager.GetString("JUserAgent_JUserAgentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string JUserAgent_Name {
            get {
                return ResourceManager.GetString("JUserAgent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while the program was running.
        /// </summary>
        internal static string Log_Error_In_Work {
            get {
                return ResourceManager.GetString("Log_Error_In_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
