//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrwSoftware {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrwCRUDRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrwCRUDRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrwSoftware.FrwCRUDRes", typeof(FrwCRUDRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( Childs).
        /// </summary>
        public static string @__Childs_ {
            get {
                return ResourceManager.GetString("__Childs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active document window.
        /// </summary>
        public static string ActiveDocumentWindow {
            get {
                return ResourceManager.GetString("ActiveDocumentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All documents.
        /// </summary>
        public static string AllDocuments {
            get {
                return ResourceManager.GetString("AllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All documents expect active.
        /// </summary>
        public static string AllDocumentsExpectActive {
            get {
                return ResourceManager.GetString("AllDocumentsExpectActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All windows.
        /// </summary>
        public static string AllWindows {
            get {
                return ResourceManager.GetString("AllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application allready running!.
        /// </summary>
        public static string Application_Allready_Running {
            get {
                return ResourceManager.GetString("Application_Allready_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local database directory was not found by the path:.
        /// </summary>
        public static string Application_Folder_Not_Found {
            get {
                return ResourceManager.GetString("Application_Folder_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Font.
        /// </summary>
        public static string Application_Font {
            get {
                return ResourceManager.GetString("Application_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string Application_settings {
            get {
                return ResourceManager.GetString("Application_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string AppSettingsWindow_Title {
            get {
                return ResourceManager.GetString("AppSettingsWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application.
        /// </summary>
        public static string BaseApplicationContext_Exit {
            get {
                return ResourceManager.GetString("BaseApplicationContext_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification!.
        /// </summary>
        public static string BaseApplicationContext_Notification {
            get {
                return ResourceManager.GetString("BaseApplicationContext_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show main window on application startup.
        /// </summary>
        public static string BaseApplicationContext_Show_Main_Window_OnStartup {
            get {
                return ResourceManager.GetString("BaseApplicationContext_Show_Main_Window_OnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show main application window.
        /// </summary>
        public static string BaseApplicationContext_ShowMainWindow {
            get {
                return ResourceManager.GetString("BaseApplicationContext_ShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies report.
        /// </summary>
        public static string BaseListWindow_DependenciesReport {
            get {
                return ResourceManager.GetString("BaseListWindow_DependenciesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        public static string BaseMainAppForm_CloseContainerWindow {
            get {
                return ResourceManager.GetString("BaseMainAppForm_CloseContainerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide main application window.
        /// </summary>
        public static string BaseMainAppForm_HideMainApplicationWindow {
            get {
                return ResourceManager.GetString("BaseMainAppForm_HideMainApplicationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open new container window.
        /// </summary>
        public static string BaseMainAppForm_OpenNewContainerWindow {
            get {
                return ResourceManager.GetString("BaseMainAppForm_OpenNewContainerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choise.
        /// </summary>
        public static string Choise {
            get {
                return ResourceManager.GetString("Choise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close....
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application.
        /// </summary>
        public static string CloseApplication {
            get {
                return ResourceManager.GetString("CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common settings.
        /// </summary>
        public static string Common_settings {
            get {
                return ResourceManager.GetString("Common_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionaries.
        /// </summary>
        public static string Dictionaries {
            get {
                return ResourceManager.GetString("Dictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this dependency.
        /// </summary>
        public static string Do_not_show_this_dependency {
            get {
                return ResourceManager.GetString("Do_not_show_this_dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download widget placement from this entry.
        /// </summary>
        public static string Download_widget_placement_from_this_entry {
            get {
                return ResourceManager.GetString("Download_widget_placement_from_this_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI Awareness Support for Windows Fonts.
        /// </summary>
        public static string DPI_Awareness_Support_for_Windows_Fonts {
            get {
                return ResourceManager.GetString("DPI_Awareness_Support_for_Windows_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI Awareness Support for Windows Fonts (&gt;= Windows 8). Application restart required..
        /// </summary>
        public static string DPI_Awareness_Support_for_Windows_Fonts_____Windows_8___Application_restart_required_ {
            get {
                return ResourceManager.GetString("DPI_Awareness_Support_for_Windows_Fonts_____Windows_8___Application_restart_requi" +
                        "red_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copied.
        /// </summary>
        public static string Drag_Copied {
            get {
                return ResourceManager.GetString("Drag_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Drag_Copy {
            get {
                return ResourceManager.GetString("Drag_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Drag_Move {
            get {
                return ResourceManager.GetString("Drag_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record successfully.
        /// </summary>
        public static string Drag_Record_Successfully {
            get {
                return ResourceManager.GetString("Drag_Record_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moved.
        /// </summary>
        public static string Drage_Moved {
            get {
                return ResourceManager.GetString("Drage_Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable floating.
        /// </summary>
        public static string EnableFloating {
            get {
                return ResourceManager.GetString("EnableFloating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error and notification console.
        /// </summary>
        public static string Error_and_notification_console {
            get {
                return ResourceManager.GetString("Error_and_notification_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for field.
        /// </summary>
        public static string For_filed {
            get {
                return ResourceManager.GetString("For_filed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new password.
        /// </summary>
        public static string Generate_new_password {
            get {
                return ResourceManager.GetString("Generate_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job &quot;.
        /// </summary>
        public static string Job__ {
            get {
                return ResourceManager.GetString("Job__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job batch &quot;.
        /// </summary>
        public static string Job_batch__ {
            get {
                return ResourceManager.GetString("Job_batch__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs and notifications.
        /// </summary>
        public static string Jobs_and_notifications {
            get {
                return ResourceManager.GetString("Jobs_and_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill job batch thread.
        /// </summary>
        public static string Kill_job_batch_thread {
            get {
                return ResourceManager.GetString("Kill_job_batch_thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill job thread.
        /// </summary>
        public static string Kill_job_thread {
            get {
                return ResourceManager.GetString("Kill_job_thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add chilld record.
        /// </summary>
        public static string List_Add_Child_Record {
            get {
                return ResourceManager.GetString("List_Add_Child_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add record.
        /// </summary>
        public static string List_Add_Record {
            get {
                return ResourceManager.GetString("List_Add_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new toplevel record.
        /// </summary>
        public static string List_Add_TopLevel_Record {
            get {
                return ResourceManager.GetString("List_Add_TopLevel_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete because there are child records.
        /// </summary>
        public static string List_Can_Not_Delete_Children {
            get {
                return ResourceManager.GetString("List_Can_Not_Delete_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Record.
        /// </summary>
        public static string List_CloneRecord {
            get {
                return ResourceManager.GetString("List_CloneRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List columns.
        /// </summary>
        public static string List_Columns {
            get {
                return ResourceManager.GetString("List_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string List_Copy {
            get {
                return ResourceManager.GetString("List_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy record to Clipboard.
        /// </summary>
        public static string List_Copy_To_Clipboard {
            get {
                return ResourceManager.GetString("List_Copy_To_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to buffer in OLV format.
        /// </summary>
        public static string List_Copy_To_Clipboard_OLV {
            get {
                return ResourceManager.GetString("List_Copy_To_Clipboard_OLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new record.
        /// </summary>
        public static string List_Create_New_Record {
            get {
                return ResourceManager.GetString("List_Create_New_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string List_Cut {
            get {
                return ResourceManager.GetString("List_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all records. If you agree with this - click &quot;Yes&quot;.
        /// </summary>
        public static string List_Delete_All_records_Confirmation {
            get {
                return ResourceManager.GetString("List_Delete_All_records_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the entry. If you agree with this - click &quot;Yes&quot;.
        /// </summary>
        public static string List_Delete_Record_Confirmation {
            get {
                return ResourceManager.GetString("List_Delete_Record_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details record info.
        /// </summary>
        public static string List_Details_Info {
            get {
                return ResourceManager.GetString("List_Details_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit field.
        /// </summary>
        public static string List_Edit_Field {
            get {
                return ResourceManager.GetString("List_Edit_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit record.
        /// </summary>
        public static string List_Edit_Record {
            get {
                return ResourceManager.GetString("List_Edit_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records.
        /// </summary>
        public static string List_No_Records {
            get {
                return ResourceManager.GetString("List_No_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected records.
        /// </summary>
        public static string List_No_Selected_Records {
            get {
                return ResourceManager.GetString("List_No_Selected_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open property windows in a modal dialog.
        /// </summary>
        public static string List_Open_In_Dialog {
            get {
                return ResourceManager.GetString("List_Open_In_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from internal application clipboard.
        /// </summary>
        public static string List_Paste_From_Buffer {
            get {
                return ResourceManager.GetString("List_Paste_From_Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from Windowsl clipboard.
        /// </summary>
        public static string List_Paste_From_Windows_Buffer {
            get {
                return ResourceManager.GetString("List_Paste_From_Windows_Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list.
        /// </summary>
        public static string List_Refresh_List {
            get {
                return ResourceManager.GetString("List_Refresh_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all records.
        /// </summary>
        public static string List_Remove_All_Records {
            get {
                return ResourceManager.GetString("List_Remove_All_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove record.
        /// </summary>
        public static string List_Remove_Record {
            get {
                return ResourceManager.GetString("List_Remove_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string List_Save_List {
            get {
                return ResourceManager.GetString("List_Save_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more than one record.
        /// </summary>
        public static string List_Selected_More_Than_On_record {
            get {
                return ResourceManager.GetString("List_Selected_More_Than_On_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List settings.
        /// </summary>
        public static string List_Settings {
            get {
                return ResourceManager.GetString("List_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics for list records.
        /// </summary>
        public static string List_Statistics {
            get {
                return ResourceManager.GetString("List_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View fileld.
        /// </summary>
        public static string List_View_Field {
            get {
                return ResourceManager.GetString("List_View_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View record.
        /// </summary>
        public static string List_View_Of_Record {
            get {
                return ResourceManager.GetString("List_View_Of_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto calc. height.
        /// </summary>
        public static string ListSettingDialogcs_AutoCalcHeight {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_AutoCalcHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string ListSettingDialogcs_Border {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ListSettingDialogcs_Details {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click.
        /// </summary>
        public static string ListSettingDialogcs_DoubleClick {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable:.
        /// </summary>
        public static string ListSettingDialogcs_Editable {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_Editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2 Only.
        /// </summary>
        public static string ListSettingDialogcs_F2Only {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_F2Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Groups.
        /// </summary>
        public static string ListSettingDialogcs_Groups {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Item:.
        /// </summary>
        public static string ListSettingDialogcs_HotItem {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_HotItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Icon.
        /// </summary>
        public static string ListSettingDialogcs_LargeIcon {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_LargeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightbox.
        /// </summary>
        public static string ListSettingDialogcs_Lightbox {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_Lightbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ListSettingDialogcs_List {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List settings.
        /// </summary>
        public static string ListSettingDialogcs_ListSettings {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_ListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView&apos;s cannot show groups when in List view..
        /// </summary>
        public static string ListSettingDialogcs_ListViewSCannotShowGroupsWhenInListView {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_ListViewSCannotShowGroupsWhenInListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft says that Tile view can&apos;t have checkboxes, so CheckBoxes have been turned off on this list..
        /// </summary>
        public static string ListSettingDialogcs_MicrosoftSaysThatTileViewCanTHaveCheckboxesSoCheckBoxesHaveBeenTurnedOffOnThisList {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_MicrosoftSaysThatTileViewCanTHaveCheckboxesSoCheckBoxesHaveBe" +
                        "enTurnedOffOnThisList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ListSettingDialogcs_No {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ListSettingDialogcs_None {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row &amp;Height:.
        /// </summary>
        public static string ListSettingDialogcs_RowHeight {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_RowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Click.
        /// </summary>
        public static string ListSettingDialogcs_SingleClick {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_SingleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Icon.
        /// </summary>
        public static string ListSettingDialogcs_SmallIcon {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_SmallIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Microsoft says that virtual lists can&apos;t use Tile view..
        /// </summary>
        public static string ListSettingDialogcs_SorryMicrosoftSaysThatVirtualListsCanTUseTileView {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_SorryMicrosoftSaysThatVirtualListsCanTUseTileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        public static string ListSettingDialogcs_TextColor {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ListSettingDialogcs_Tile {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translucent.
        /// </summary>
        public static string ListSettingDialogcs_Translucent {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_Translucent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View:.
        /// </summary>
        public static string ListSettingDialogcs_View {
            get {
                return ResourceManager.GetString("ListSettingDialogcs_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list.
        /// </summary>
        public static string Lisе_Refresh_List {
            get {
                return ResourceManager.GetString("Lisе_Refresh_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load configuration.
        /// </summary>
        public static string LoadConfiguration {
            get {
                return ResourceManager.GetString("LoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window.
        /// </summary>
        public static string Main_Window {
            get {
                return ResourceManager.GetString("Main_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one entry selected.
        /// </summary>
        public static string More_than_one_entry_selected {
            get {
                return ResourceManager.GetString("More_than_one_entry_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This drag&amp;drop is not possible. The source or destination does not allow this operation..
        /// </summary>
        public static string Move_Not_Allowed_1 {
            get {
                return ResourceManager.GetString("Move_Not_Allowed_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This drag&amp;drop is not possible. You can only transfer to the area of a specific line in the list..
        /// </summary>
        public static string Move_Not_Allowed_2 {
            get {
                return ResourceManager.GetString("Move_Not_Allowed_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item selected.
        /// </summary>
        public static string No_item_selected {
            get {
                return ResourceManager.GetString("No_item_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is impossible. Insufficient access rights..
        /// </summary>
        public static string NO_RIGHTS {
            get {
                return ResourceManager.GetString("NO_RIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string Not_present {
            get {
                return ResourceManager.GetString("Not_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications and events.
        /// </summary>
        public static string Notifications_and_events {
            get {
                return ResourceManager.GetString("Notifications_and_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item found to display.
        /// </summary>
        public static string Object_For_View_Not_Found {
            get {
                return ResourceManager.GetString("Object_For_View_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Yes&apos; to convert html text to plain text and edit it with plain text editor (all HTML formating will be lost) or press &apos;No&apos; to still edit html text.
        /// </summary>
        public static string Press__Yes__to_convert_html_text_to_plain_text_and_edit_it_with_plain_text_editor__all_HTML_formating_will_be_lost__or_press__No__to_still_edit_html_text {
            get {
                return ResourceManager.GetString("Press__Yes__to_convert_html_text_to_plain_text_and_edit_it_with_plain_text_editor" +
                        "__all_HTML_formating_will_be_lost__or_press__No__to_still_edit_html_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Yes&apos; to convert plain text to html and edit it with html editor or press &apos;No&apos; to still edit plain text.
        /// </summary>
        public static string Press__Yes__to_convert_plain_text_to_html_and_edit_it_with_html_editor_or_press__No__to_still_edit_plain_text {
            get {
                return ResourceManager.GetString("Press__Yes__to_convert_plain_text_to_html_and_edit_it_with_html_editor_or_press__" +
                        "No__to_still_edit_plain_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record can not be empty.
        /// </summary>
        public static string Record_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Record_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all entities data.
        /// </summary>
        public static string Save_all_entities_data {
            get {
                return ResourceManager.GetString("Save_all_entities_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current widget placement to this entry.
        /// </summary>
        public static string Save_current_widget_placement_to_this_entry {
            get {
                return ResourceManager.GetString("Save_current_widget_placement_to_this_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration.
        /// </summary>
        public static string SaveConfiguration {
            get {
                return ResourceManager.GetString("SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select field insert to.
        /// </summary>
        public static string SelectFieldToPaste {
            get {
                return ResourceManager.GetString("SelectFieldToPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set NULL.
        /// </summary>
        public static string Set_NULL {
            get {
                return ResourceManager.GetString("Set_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show job batch console.
        /// </summary>
        public static string Show_job_batch_console {
            get {
                return ResourceManager.GetString("Show_job_batch_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show job console.
        /// </summary>
        public static string Show_job_console {
            get {
                return ResourceManager.GetString("Show_job_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show documents icons.
        /// </summary>
        public static string ShowDocumentsIcons {
            get {
                return ResourceManager.GetString("ShowDocumentsIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file copy.
        /// </summary>
        public static string SimpleAttachmentsDialog_AddFileCopy {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_AddFileCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder reference.
        /// </summary>
        public static string SimpleAttachmentsDialog_AddFolderRef {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_AddFolderRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file reference.
        /// </summary>
        public static string SimpleAttachmentsDialog_AddRef {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_AddRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add URL.
        /// </summary>
        public static string SimpleAttachmentsDialog_AddUrl {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_AddUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacments.
        /// </summary>
        public static string SimpleAttachmentsDialog_Attachments {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string SimpleAttachmentsDialog_CreationDate {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of file.
        /// </summary>
        public static string SimpleAttachmentsDialog_FileType {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification date.
        /// </summary>
        public static string SimpleAttachmentsDialog_ModificationDate {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_ModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string SimpleAttachmentsDialog_OpenFile {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string SimpleAttachmentsDialog_OpenFolder {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string SimpleAttachmentsDialog_Path {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SimpleAttachmentsDialog_Size {
            get {
                return ResourceManager.GetString("SimpleAttachmentsDialog_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear time.
        /// </summary>
        public static string SimpleDateTimeDialog_ClearTime {
            get {
                return ResourceManager.GetString("SimpleDateTimeDialog_ClearTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string SimpleDateTimeDialog_Date_And_Time {
            get {
                return ResourceManager.GetString("SimpleDateTimeDialog_Date_And_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        public static string SimpleDictListDialog_Dict {
            get {
                return ResourceManager.GetString("SimpleDictListDialog_Dict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string SimpleDictListDialog_Image {
            get {
                return ResourceManager.GetString("SimpleDictListDialog_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SimpleDictListDialog_Name {
            get {
                return ResourceManager.GetString("SimpleDictListDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string SimpleJDictItemDialog_Image {
            get {
                return ResourceManager.GetString("SimpleJDictItemDialog_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string SimpleJDictItemDialog_Key {
            get {
                return ResourceManager.GetString("SimpleJDictItemDialog_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string SimpleJDictItemDialog_Text {
            get {
                return ResourceManager.GetString("SimpleJDictItemDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary record.
        /// </summary>
        public static string SimpleJDictItemDialog_Title {
            get {
                return ResourceManager.GetString("SimpleJDictItemDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string SimpleListDialog_Title {
            get {
                return ResourceManager.GetString("SimpleListDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string SimpleMultivalueDictFieldItemListDialog_Image {
            get {
                return ResourceManager.GetString("SimpleMultivalueDictFieldItemListDialog_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SimpleMultivalueDictFieldItemListDialog_Name {
            get {
                return ResourceManager.GetString("SimpleMultivalueDictFieldItemListDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection list of dictionary.
        /// </summary>
        public static string SimpleMultivalueDictFieldItemListDialog_Title {
            get {
                return ResourceManager.GetString("SimpleMultivalueDictFieldItemListDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SimpleMultivalueFieldItemListDialog_Id {
            get {
                return ResourceManager.GetString("SimpleMultivalueFieldItemListDialog_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SimpleMultivalueFieldItemListDialog_Name {
            get {
                return ResourceManager.GetString("SimpleMultivalueFieldItemListDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection list.
        /// </summary>
        public static string SimpleMultivalueFieldItemListDialog_Title {
            get {
                return ResourceManager.GetString("SimpleMultivalueFieldItemListDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Dialog.
        /// </summary>
        public static string SimplePropertyDialog_Title {
            get {
                return ResourceManager.GetString("SimplePropertyDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute: .
        /// </summary>
        public static string SimplePropertyWindow_Attribute {
            get {
                return ResourceManager.GetString("SimplePropertyWindow_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - properies.
        /// </summary>
        public static string SimplePropertyWindow_Props {
            get {
                return ResourceManager.GetString("SimplePropertyWindow_Props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record properties.
        /// </summary>
        public static string SimplePropertyWindow_Title {
            get {
                return ResourceManager.GetString("SimplePropertyWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text.
        /// </summary>
        public static string SimpleTextDialog_EnterText {
            get {
                return ResourceManager.GetString("SimpleTextDialog_EnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string SimpleTextEditDialog_Title {
            get {
                return ResourceManager.GetString("SimpleTextEditDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusbar.
        /// </summary>
        public static string Statusbar {
            get {
                return ResourceManager.GetString("Statusbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are new notifications and events.
        /// </summary>
        public static string There_are_new_notifications_and_events {
            get {
                return ResourceManager.GetString("There_are_new_notifications_and_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is readonly.
        /// </summary>
        public static string This_field_is_readonly {
            get {
                return ResourceManager.GetString("This_field_is_readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate new password press &quot;Yes&quot; .
        /// </summary>
        public static string To_generate_new_password_press__Yes__ {
            get {
                return ResourceManager.GetString("To_generate_new_password_press__Yes__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        public static string Toolbar {
            get {
                return ResourceManager.GetString("Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string TreeList_Loading {
            get {
                return ResourceManager.GetString("TreeList_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to cancel job.
        /// </summary>
        public static string Try_to_cancel_job {
            get {
                return ResourceManager.GetString("Try_to_cancel_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to cancel job batch.
        /// </summary>
        public static string Try_to_cancel_job_batch {
            get {
                return ResourceManager.GetString("Try_to_cancel_job_batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update current configuration.
        /// </summary>
        public static string UpdateCurrentConfiguration {
            get {
                return ResourceManager.GetString("UpdateCurrentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget&apos;s configuration.
        /// </summary>
        public static string WidgetSConfiguration {
            get {
                return ResourceManager.GetString("WidgetSConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center main window and set size 75% of screen.
        /// </summary>
        public static string Window_Center_75 {
            get {
                return ResourceManager.GetString("Window_Center_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong operation.
        /// </summary>
        public static string Wrong_Operation {
            get {
                return ResourceManager.GetString("Wrong_Operation", resourceCulture);
            }
        }
    }
}
